categories:
  Excluded:
    color: "#2C3E50"
    keywords:
      - american express ach pmt
      - payment to chase card
      - vanguard buy
      - kraken
      - venmo
      - Payment Thank You-Mobile
      - MOBILE PAYMENT - THANK YOU
      - "to SAV ...7723"
      - "from SAV ...7723"

  Requires Manul categorization:
    color: "#FFFFFF"
    keywords: 
      - amex dining credit

  Income:
    color: "#2ECC71"
    keywords:
      - payroll
      - direct dep
      - ach credit
      - dividend
      - interest paid

  Groceries:
    color: "#ADD8E6"
    keywords:
      - instacart
      - wholefood
      - trader joe
      - kroger
      - albertsons
      - save mart
      - 99 ranch
      - mitsuwa
      - safeway
      - ralphs
      - sprouts
      - vons
      - northgate
      - grocery outlet
      - la posta market
      - superior super
      - el super
      - liquor mart anaheim ca
      - Water Gourmet Anaheim CA
  
  Food & Drink:
    color: "#FF6B6B"
    keywords:
      - JOE  THE JUICE SFO L San Francisco CA
      - jamba juice
      - doordash
      - uber eats
      - grubhub
      - ELPOLLOLOCO
      - taco bell
      - del taco
      - chipotle
      - el tijuanazo
      - carnitas el rey
      - tacos los cholos
      - tacos el patron
      - taco stand
      - TAQUEANAHEIM
      - primecut
      - los de juarez
      - taco
      - DLRBUENAVISTACHURRO
      - dlr ice cream
      - paradise smoke shop
      - teddys deli
      - willys eatery
      - mcdonald
      - burger king
      - wendy's
      - jack in the box
      - carls jr
      - in-n-out
      - habit
      - 5guys
      - burger
      - Little Caesars
      - pizza hut
      - blaze
      - domino
      - chick-fil-a
      - popeyes
      - kfc
      - raising canes
      - DAVESHOTCHICKEN
      - wingstop
      - 7-eleven
      - platinum liquor
      - 'world oil #75 san jose'
      - stadium liquor anaheim
      - college drive in anaheim
      - hudsonnews
      - hudson book st
      - chinese food
      - panda express
      - hong kong express
      - hot dog
      - sandwich
      - kookoo grill
      - mendocino
      - panera
      - subway
      - board and brew
      - poke
      - pokinometry
      - craftbowl
      - fruit
      - cookie
      - krispy kreme
      - donut
      - baskin

  
  Dining Out:
    color: "#FF8E53"
    keywords:
      - restaurant
      - grill
      - kitchen
      - bistro
      - pizza
      - sushi
      - diner
      - eatery
      - terra laguna
      - tst*terra
      - tst* ballast point
      - pho holy
      - brewing
      - stadium pepz
      - cruisers
      - thegarret
      - tst* el porteno
      - villains
      - rock a los angeles
      - ramen
      - shabu
      - red robin

  Vices: 
    color: "#C1685B"
    keywords:
      - anaheim smoke shop
      - smoke and vape
      - fox pub
      - dlr oga's cantina
      - dlr paradise beer
      - magic land market
      - paper plane
      - muldoons irish newport beach
      - bar
      - pub
      - tst* the biergarten
      - nv lounge anaheim
      - smoke shop

  Coffee:
    color: "#6F4E37"
    keywords: 
      - 7 leaves
      - 7leaves
      - BETTERBUZZ
      - dutchbros
      - dutch bros
      - moongoat
      - coffee
      - tea
      - dunkin
      - starbucks

  Transportation:
    color: "#4ECDC4"
    keywords:
      - uber
      - lyft
      - metro
      - parking
      - SPOTHERO
      - parkmobile
      - city of newport beac
      - uci tds
      - chevron
      - shell
      - arco
      - costco gas
      - exxon
      - bp gas
      - speedway
      - circle k
      - fuel
      - WAVE-1

  Shopping:
    color: "#45B7D1"
    keywords:
      - amazon
      - amzn
      - target
      - walmart
      - WAL-MART
      - kohls
      - hobbylobb
      - DEPOP
      - best buy
      - home depot
      - ikea
      - marshalls
      - tj maxx
      - nordstrom
      - h&m
      - uniqlo
      - macy
      - ebay
      - etsy
      - ECO TOWN
      - sporting goods
      - dollar tree
      - dollar tr
      - lush
      - claire's
      - golfwang
      - basketcase
      - lonely star
      - little light - bp
      - zagg
      - k-pop
      - k- pop
      - k+pop
      - house of intuition
      - fragrancenet
      - jomashop
      - redbubble
      - dhgate
      - fanatics

  Health & Fitness:
    color: "#96CEB4"
    keywords:
      - cvs
      - walgreens
      - rite aid
      - pharmacy
      - doctor
      - dental
      - vision
      - gym
      - beach city sp
      - planet fitness
      - equinox
      - medical
      - KP SCAL
      - kaiser

  Entertainment:
    color: "#9B59B6"
    keywords:
      - netflix
      - spotify
      - hulu
      - disney
      - apple.com/bill
      - google play
      - steam
      - playstation
      - xbox
      - amc
      - cinemark
      - ticketmaster
      - "axs.com"
      - tcktweb
      - tickpick
      - glfmesa
      - glf*mesa
      - glf*nbgc
      - THEISLANDSGOLFCENTER
      - oso creek golf
      - rancho san joaquin 4110
      - mile square golf
      - lake forrest 199 ps lake forest ca
      - uci e-tickets
      - fandango
      - museum
      - zoo
      - 91114-treetops canteen
      - karaoke
      - intuit dome
      - sofi sta
      - the island golf
      - alcatraz
    amount_keywords:
      - description: APPLE.COM/BILL
        amount: 12.99


  Travel:
    color: "#3498DB"
    keywords:
      - airline
      - airbnb
      - hotel
      - marriott
      - hilton
      - delta
      - frontier
      - united
      - american air
      - southwest
      - expedia
      - booking.com
      - amex trvl


  Bills & Utilities:
    color: "#E74C3C"
    keywords:
      - att
      - verizon
      - t-mobile
      - comcast
      - xfinity
      - spectrum
      - electric
      - gas company
      - water bill
      - insurance
      - geico
      - state farm
    amount_keywords:
      - description: zelle payment to miguel
        amount: 195.00
      - description: zelle payment to miguel
        amount: 87.00
      - description: APPLE.COM/BILL
        amount: 2.99

  Personal Care:
    color: "#F39C12"
    keywords:
      - salon
      - barber
      - ulta
      - sephora
      - 5 star cleaners # hemming clothes




  Rent:
    color: "#E67E22"
    keywords:
      - bilt payment
      - biltrent
      - greystar

  Student Loans:
    color: "#8E44AD"
    keywords:
      - advs ed serv
      - studntloan
      - educational comp
      - epayment
  

  Car Payment:
    color: "#C0392B"
    keywords:
      - sdccu

  Auto Services:
    color: "#E74C3C"
    keywords:
      - an honda
      - honda costa mesa
      - hardin honda
      - soap city
      - CULVER AUTO SPA IRVINE CA
      - smog check

  Professional Development:
    color: "#2980B9"
    keywords:
      - vue testing exam
      - wl *vue*
      - squarespace


  Zelle, & Paypal:
    color: "#5B8CDB"
    keywords:
      - zelle
      - paypal
      - apple cash sent

  Transfer:
    color: "#95A5A6"
    keywords:
      - acct xfer
      - transfer

  ATM & Cash:
    color: "#7F8C8D"
    keywords:
      - atm withdrawal
      - non-chase atm

  Fines & Fees:
    color: "#D35400"
    keywords:
      - st of ca dmv
      - orange county su payment
      - state of calif dmv
      - dmv fee

  Taxes: 
    color: "#757484"
    keywords: 
      - freetaxusa
      - tax ref
      - tax bd

  Miscellaneous: 
    color: "#D3D3D3"
    keywords:
      - usps
      - ups


  Uncategorized:
    color: "#BDC3C7"
    keywords: []